package com.glue.webapp.beans;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.inject.Inject;
import javax.inject.Named;

import org.omnifaces.cdi.Param;
import org.omnifaces.cdi.ViewScoped;
import org.omnifaces.cdi.param.ParamValue;

import com.glue.webapp.logic.EventController;

@Named
@ViewScoped
public class EventSearchBean extends StreamSearchBean implements Serializable {

    private static final String VIEW_ID = "/stream/search.xhtml";
    private String location;
    private double latitude;
    private double longitude;

    @Inject
    @Param
    // Like <f:viewParam name="q" value="#{bean.q}">
    private ParamValue<String> q;

    @Inject
    @Param
    // Location
    private ParamValue<String> ql;

    @Inject
    @Param
    // Latitude
    private ParamValue<Double> lat;

    @Inject
    @Param
    // Longitude
    private ParamValue<Double> lng;

    @Inject
    private transient EventController controller;

    public String getLocation() {
	return location;
    }

    public void setLocation(String location) {
	this.location = location;
    }

    public double getLatitude() {
	return latitude;
    }

    public void setLatitude(double latitude) {
	this.latitude = latitude;
    }

    public double getLongitude() {
	return longitude;
    }

    public void setLongitude(double longitude) {
	this.longitude = longitude;
    }

    @PostConstruct
    private void init() {
	String rowsPerPageParam = FacesUtil
		.getRequestParameter(QueryParams.ROWS_PER_PAGE);
	if (rowsPerPageParam != null) {
	    setRowsPerPage(Integer.valueOf(rowsPerPageParam));
	}
	setQuery(q.getValue());

	location = ql.getValue();
	if (lat.getValue() != null && lng.getValue() != null) {
	    latitude = lat.getValue();
	    longitude = lng.getValue();
	}

	first();
    }

    public String search0() {

	FacesContext ctx = FacesContext.getCurrentInstance();
	String viewId = ctx.getViewRoot().getViewId();
	if (VIEW_ID.equals(viewId)) {
	    first();
	    return null;
	}

	// Pass temporary view params between the user views generated by the
	// faces lifecycle. The view params will be exposed to the next view
	// encountered by the same user session and then cleared out.
	Flash flash = ctx.getExternalContext().getFlash();
	flash.put(QueryParams.QUERY_STRING, getQuery());
	flash.put(QueryParams.LOCATION, this.location);
	flash.put(QueryParams.LATITUDE, this.latitude);
	flash.put(QueryParams.LONGITUDE, this.longitude);

	// Redirect
	return VIEW_ID + "?faces-redirect=true&amp;includeViewParams=true";
    }

    @Override
    public Void search() throws Exception {

	// Common params
	controller.setQueryString(getQuery());
	controller.setStartDate(getStartDate());
	controller.setEndDate(getEndDate());
	controller.setCategories(getCatSelection());

	// Specific params
	controller.setLocation(location);
	controller.setLatitude(latitude);
	controller.setLongitude(longitude);

	// Pagination controls
	controller.setStart(getStart());
	controller.setRowsPerPage(getRowsPerPage());

	this.events = controller.search();

	// Update the total number of rows
	setTotalRows(controller.getTotalRows());

	return null;
    }

}
